name: bankingassistant
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^1.2.0
  mysql1: ^0.16.3
  flutter_charts: ^0.1.10
  carousel_slider: ^1.1.0
  mongo_dart: ^0.3.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/backg.jpg
   - assets/backg1.jpg
   - assets/appicon.png
   - assets/calLogo.png
   - assets/ecoLogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: a
      fonts:
        - asset: fonts/a-regular.otf
        - asset: fonts/a-dingbats.otf
    - family: b
      fonts:
        - asset: fonts/b-regular.otf
        - asset: fonts/b-slant.otf
          weight: 700
    - family: c
      fonts:
        - asset: fonts/c-regular.ttf
    - family: d
      fonts:
        - asset: fonts/d-regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
